### ISSUE TITLE
Documention on Aliases

### ISSUE THREAD

**Issue by RDK-45** [postfixadmin/postfixadmin#658]
OK, the documentation for using PostfixAdmin is a bit sparse, but for the most part I have figured it all out.  However, it is not clear the difference between the Aliases as part of the "Aliases" block vs those in the "Mailbox" users line.  

Can someone elaborate or point me to some references? Thanks...RDK45

**Comment by DavidGoodwin** [comment]
For historical reasons, PostfixAdmin stores one record for the alias (comma separated values) - e.g. 

```
MariaDB [postfixadmin]> select * from alias where address = 'test@example.com' \G
*************************** 1. row ***************************
 address: test@example.com
    goto: blah@test.com,test@example.com
  domain: example.com
 created: 2021-05-13 13:04:33
modified: 2022-07-12 20:31:23
  active: 1
1 row in set (0.001 sec)
```

and the associated mailbox entity - 

```
MariaDB [postfixadmin]> select * from mailbox where username = 'test@example.com' \G
*************************** 1. row ***************************
       username: test@example.com
       password: ....
           name: test person
        maildir: example.com/test/
          quota: 1024000000
     local_part: test
         domain: example.com
        created: 2021-05-13 13:04:33
       modified: 2022-07-12 20:29:03
         active: 1
          phone: 
    email_other: 
          token: 
 token_validity: 2021-05-13 13:04:33
password_expiry: 2023-07-12 20:29:00
1 row in set (0.002 sec)
```

So if you emailed test@exmaple.com, a copy would go to the mailbox, and a copy would be delivered to blah@test.com.


From Postfix's point of view - Postfix does a lookup on the RCPT TO address provided, and if it finds a match in the alias table it's happy. To make this easy, we have an 'alias' record for every 'mailbox'. 

So as a minimum you may have an alias which points to the mailbox - like so : 


```
MariaDB [postfixadmin]> select * from alias where address = 'pickle@example.com' \G
*************************** 1. row ***************************
 address: pickle@example.com
    goto: pickle@example.com
  domain: example.com
 created: 2021-12-15 21:14:18
modified: 2022-10-10 16:31:13
  active: 1
1 row in set (0.002 sec)
```

```
MariaDB [postfixadmin]> select * from mailbox where username = 'pickle@example.com' \G
*************************** 1. row ***************************
       username: pickle@example.com
       password: ...
           name: pickle 
        maildir: example.com/pickle/
          quota: 1024000
     local_part: pickle
         domain: example.com
        created: 2021-12-15 21:14:18
       modified: 2022-07-30 21:22:51
         active: 1
          phone: 
    email_other: 
          token: 
 token_validity: 2021-12-15 21:14:18
password_expiry: 2022-12-15 21:14:00
1 row in set (0.001 sec)
```
